services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:XXXperu2020XXX.@161.132.54.103:3306/confejas_2025
      CORS_ORIGIN: http://confejas2025.site
    networks:
      - shared_network

networks:
  shared_network:
    external: true
